version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      WEBPACK_SERVER_PORT: 8080
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACK_END_API_URL: http://backend:3000
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
